import { ArticleItem } from '../types';

export const ARTICLES_DATA: ArticleItem[] = [
  {
    id: 'ecommerce-roadmap',
    title: 'از ایده اولیه تا ثبت نخستین تراکنش آنلاین؛ نقشه راه گام‌به‌گام راه‌اندازی فروشگاه مدرن',
    slug: 'ecommerce-success-roadmap',
    category: 'تجارت الکترونیک B2C',
    categoryKey: 'ecommerce',
    readTime: '۸ دقیقه',
    date: '۲ روز پیش',
    author: 'تیم تحریریه محصول علاءالدین',
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBLsax6qFpkuzgzY-yU83CtcVM05kXZciyufSTsZ-c2_Zg0YtSv2NLxoJaTsnaC9F1mEKhlJtUb3VZYEJw8J4nSkftynjCDSOPW3KoOzJ6A2XVU0iwyGUjBWArlQikJwdKwiIEsCKzDGwQIbi9hvlden7uUA9omz4vprPc63ssbfdj_A6Rvc2PiNhxBzs12_2NEZBa0lbqTpFkOMpOKoKmPYNqncwLImR84KvKVV1KZ3wZn3Hn7V6e6',
    summary: 'چگونه با معماری درست، یک فروشگاه با لود زیر یک ثانیه بسازیم که درگاه بانکی آن در اوج تخفیفات قطعی نداشته باشد و سریعاً در سرچ گوگل و ترب جایگاه بگیرد؟',
    featured: true,
    views: 1840,
  },
  {
    id: 'seo-first-architecture',
    title: 'طراحی سایت سئومحور یعنی چه و از چه مرحله‌ای باید شروع شود؟',
    slug: 'seo-first-architecture-guide',
    category: 'سئو و رشد',
    categoryKey: 'seo-ai',
    readTime: '۶ دقیقه',
    date: '۵ روز پیش',
    author: 'مهندس حسینی - سرپرست سئو',
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBVHts9NKYEagOabU_kV19HbLqAwt2fsWPsQXwa9M1tq_xqOFCU8yRFNlDVfDzQnKATg95Mqnx5IIoojmAWPPLoB9nUleq-UVzotXn4i3GgntHuTMDs89taEX-GDxWT5vdi_vCzHdgnJPMBq-sDvA1yh-q8xPMO6gOT8BU0H4mXfBN4xqu1cUc9uRtU6-grx76Pwh93552QOlpcl1oMrWkkYd4J6-dSG0GLKcm9JA0M6SNp-WwUNwfL',
    summary: 'بررسی ۵ فاکتور کلیدی در معماری کد و ساختار URLها که باید پیش از اولین خط طراحی، با متخصص سئو هماهنگ گردند.',
    views: 1250,
  },
  {
    id: 'ai-in-modern-web',
    title: 'هوش مصنوعی در وب‌سایت‌ها دقیقاً کجا به کار می‌آید و کجا آسیب می‌زند؟',
    slug: 'ai-in-modern-web-applications',
    category: 'AI & آینده وب',
    categoryKey: 'seo-ai',
    readTime: '۵ دقیقه',
    date: '۱ هفته پیش',
    author: 'واحد تحقیق و توسعه علاءالدین',
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAiiiZRVZ428Gt1iITfF43ftx9HOZkPCsHx79VD8fMoxE4WWkXDom6LFDik8GewR6JpqBr6jYY1tesYWfFsmdubULHA1e0Lqw1YhEL89GzQpm_PmM3wQSl0eJLTOYGwnwaKZqFwZdH1F4HIevdz_e__9EC5z6NlQ3BT019dWepIuReBgAWnoaUlTmWOZtSiZqiEzvTF_96iem2f82WheF4SQg_3_xND-z3gA4jWmCE5yWM9ZU5VIBCX',
    summary: 'چت‌بات‌های پاسخگو، جستجوی معنایی و پیش‌بینی رفتار مشتری در مقایسه با تولید متن بی‌کیفیت و خطرات جریمه گوگل.',
    views: 980,
  },
  {
    id: 'custom-vs-wordpress',
    title: 'سایت اختصاصی یا وردپرس؛ بررسی تفاوت‌های پنهان فنی',
    slug: 'custom-development-vs-wordpress',
    category: 'طراحی سایت و UI/UX',
    categoryKey: 'ui-ux',
    readTime: '۷ دقیقه',
    date: '۲ هفته پیش',
    author: 'تیم معماری نرم‌افزار',
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGor_mOPphxRbMBHrw_xHZa3EAvnXJ4HP333U2-OggtIg5IVfTJGIDBlXjJbTpBpEBx7I4X12A5xHlRsB5Ku9PAP9L8Pq6bhQUsrqu5tvlN0F_GS_uW-0JTwQ1RwyU0BprGMv9FDdPEKNOPaYgX9q_sLuDzZNekgyIvVWZEQWBfAhBaCQ7K6UyciFJzqtcvZN4l3KUwttb_SpT5GmOeMT3p-ehqB7C3WrO0N5K_EGZCV1J3lT92CfI',
    summary: 'مقایسه عادلانه هزینه‌های نگهداری، سرعت، امنیت و مقیاس‌پذیری بین سیستم‌های آماده و توسعه اختصاصی.',
    views: 1480,
  },
];
