import { ProjectItem } from '../types';

export const PROJECTS_DATA: ProjectItem[] = [
  {
    id: 'adaksteel',
    title: 'پلتفرم استعلام قیمت و بازرگانی فولاد آداک',
    category: 'صنعتی و بازرگانی',
    domain: 'adaksteel.com',
    url: 'https://adaksteel.com',
    img: 'https://aladdinweb.ir/wp-content/uploads/2025/08/adaksteel.png',
    description: 'ساختار معرفی خدمات، پروژه‌ها و اعتبارسازی برند در یک تجربه کاری ساده و حرفه‌ای. این سایت مجهز به جدول لحظه‌ای قیمت روز آهن‌آلات، ماشین‌حساب آنلاین وزن میلگرد و ورق، و استعلام خودکار پیش‌فاکتور رسمی در کمتر از ۲ دقیقه است.',
    leadResult: '+۲۴۰٪ افزایش سرنخ تلفنی',
    speed: '۰.۷ ثانیه',
    googleRank: 'رتبه ۱ گوگل در کلمات اصلی',
    mobileScore: '۱۰۰٪ بهینه موبایل',
    industry: 'صنایع فولاد و متالورژی',
    technologies: ['Next.js 14', 'Tailwind CSS', 'Redis Cache', 'PostgreSQL', 'API استعلام لحظه‌ای'],
    languages: ['fa', 'en'],
    executionTime: '۲۱ روز کاری',
    featured: true,
  },
  {
    id: 'arkabest',
    title: 'فروشگاه آنلاین قطعات صنعتی آرکابست',
    category: 'فروشگاه اینترنتی B2C / B2B',
    domain: 'arkabest.com',
    url: 'https://arkabest.com',
    img: 'https://aladdinweb.ir/wp-content/uploads/2025/08/arkabast.png',
    description: 'سامانه فروش آنلاین قطعات صنعتی با بیش از ۱۲,۰۰۰ قلم کالا، انبارداری هوشمند چند شعبه‌ای، فیلتر ویژگی‌های فنی قطعات، اتصال مستقیم به موتور جستجوی ترب و تسویه آنی درگاه شاپرک.',
    leadResult: '+۱۸۰٪ رشد فروش ماه اول',
    speed: '۰.۸ ثانیه',
    googleRank: 'لینک ۱ تا ۳ گوگل در دسته‌بندی ابزار',
    mobileScore: '۹۹٪ موبایل فرندلی',
    industry: 'ابزار و قطعات صنعتی',
    technologies: ['WooCommerce Pro', 'React Custom Cart', 'Torob API', 'سامانه پیامک الگو'],
    languages: ['fa'],
    executionTime: '۱۸ روز کاری',
    featured: true,
  },
  {
    id: 'bazsazimoon',
    title: 'استودیو معماری و طراحی داخلی بازسازی‌مون',
    category: 'خدماتی و دکوراسیون',
    domain: 'bazsazimoon.ir',
    url: 'https://bazsazimoon.ir',
    img: 'https://aladdinweb.ir/wp-content/uploads/2025/08/bazsazimoon.png',
    description: 'پورتال نمونه‌کارهای لوکس معماری، گالری قبل و بعد پروژه‌های مسکونی و تجاری، ماشین‌حساب تخمین آنلاین بودجه بازسازی هر مترمربع و تقویم رزرو هوشمند مشاوره حضوری در محل.',
    leadResult: 'بیش از ۵۰ رزرو ماهانه',
    speed: '۰.۹ ثانیه',
    googleRank: 'رتبه ۱ بازسازی خانه تهران',
    mobileScore: '۱۰۰٪ واکنش‌گرا',
    industry: 'معماری و دکوراسیون لوکس',
    technologies: ['Next.js', 'Framer Motion', 'Calendar Sync', 'WebP Optimizer'],
    languages: ['fa'],
    executionTime: '۱۴ روز کاری',
    featured: true,
  },
  {
    id: 'azarkarbitumen',
    title: 'پلتفرم صادراتی فرآورده‌های نفتی آذرکار',
    category: 'صادراتی و چندزبانه',
    domain: 'azarkarbitumen.com',
    url: 'https://azarkarbitumen.com',
    img: 'https://aladdinweb.ir/wp-content/uploads/2025/08/azarkarbitumen1.png',
    description: 'وب‌سایت چندزبانه بین‌المللی با فرم استعلام قیمت ارزی (RFQ)، آنالیز فنی قیر و فرآورده‌های پتروشیمی بر اساس استانداردهای بین‌المللی ASTM و کاتالوگ‌های دانلودی امن برای بازارهای هدف صادراتی.',
    leadResult: 'بازدید تجاری از ۲۲ کشور',
    speed: '۰.۷ ثانیه جهانی',
    googleRank: 'حضور در نتایج گوگل خاورمیانه و CIS',
    mobileScore: '۱۰۰٪ استاندارد بین‌المللی',
    industry: 'نفت، گاز و پتروشیمی',
    technologies: ['i18n Dynamic Engine', 'Cloudflare Enterprise', 'RFQ Engine', 'Bilingual CMS'],
    languages: ['fa', 'en', 'ar', 'tr'],
    executionTime: '۲۵ روز کاری',
    featured: true,
  },
  {
    id: 'novin-clinic',
    title: 'سامانه رزرواسیون و کلینیک تخصصی دکتر میرزایی',
    category: 'پزشکی و رزرواسیون',
    domain: 'dr-mirzaei.com',
    url: 'https://dr-mirzaei.com',
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGor_mOPphxRbMBHrw_xHZa3EAvnXJ4HP333U2-OggtIg5IVfTJGIDBlXjJbTpBpEBx7I4X12A5xHlRsB5Ku9PAP9L8Pq6bhQUsrqu5tvlN0F_GS_uW-0JTwQ1RwyU0BprGMv9FDdPEKNOPaYgX9q_sLuDzZNekgyIvVWZEQWBfAhBaCQ7K6UyciFJzqtcvZN4l3KUwttb_SpT5GmOeMT3p-ehqB7C3WrO0N5K_EGZCV1J3lT92CfI',
    description: 'سامانه پذیرش اینترنتی بیماران، تقویم رزرو شیفت پزشکان، ارسال پیامک یادآور، پرونده الکترونیک و پرداخت آنلاین ویزیت مطابق ضوابط سازمان نظام پزشکی.',
    leadResult: '+۳۲۰ نوبت آنلاین در ماه',
    speed: '۰.۸ ثانیه',
    googleRank: 'صفحه اول متخصص جراحی تهران',
    mobileScore: '۱۰۰٪ بهینه‌سازی شده',
    industry: 'پزشکی و سلامت',
    technologies: ['React 19', 'Node.js', 'SMS Kavenegar', 'درگاه پرداخت به پرداخت'],
    languages: ['fa', 'en'],
    executionTime: '۱۶ روز کاری',
    featured: false,
  },
  {
    id: 'holding-parskala',
    title: 'پرتال جامع هلدینگ بین‌المللی پارس کالا',
    category: 'شرکتی و هلدینگی',
    domain: 'parskala-holding.com',
    url: 'https://parskala-holding.com',
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAiiiZRVZ428Gt1iITfF43ftx9HOZkPCsHx79VD8fMoxE4WWkXDom6LFDik8GewR6JpqBr6jYY1tesYWfFsmdubULHA1e0Lqw1YhEL89GzQpm_PmM3wQSl0eJLTOYGwnwaKZqFwZdH1F4HIevdz_e__9EC5z6NlQ3BT019dWepIuReBgAWnoaUlTmWOZtSiZqiEzvTF_96iem2f82WheF4SQg_3_xND-z3gA4jWmCE5yWM9ZU5VIBCX',
    description: 'پرتال معرفی شرکت‌های تابعه، معرفی اعضای هیئت مدیره، گزارش سالانه سهام‌داران، مناقصات و مزایدات آنلاین و سیستم پذیرش سرمایه‌گذاری خارجی.',
    leadResult: 'جذب ۳ شریک بین‌المللی',
    speed: '۰.۶۵ ثانیه',
    googleRank: 'رتبه ۱ برندینگ هلدینگ سرمایه‌گذاری',
    mobileScore: '۹۸٪ آزمون سرعت',
    industry: 'سرمایه‌گذاری و تجارت بین‌الملل',
    technologies: ['Next.js 14', 'TypeScript', 'Tailwind', 'Headless CMS'],
    languages: ['fa', 'en', 'ar', 'de'],
    executionTime: '۲۸ روز کاری',
    featured: false,
  },
];
